"INSERT INTO public.board_game (id, title, title_normalized, description, min_players, max_players, min_age, max_age, estimated_play_time, can_play_only_once, is_extension, tutorial_url) VALUES (1, 'Stranger Things: Obrácený svět', 'stranger things: obraceny svet', '', 2, 4, 12, NULL, 60, false, false, 'https://www.youtube.com/watch?v=GJxO3mwow5c');"
"INSERT INTO public.board_game (id, title, title_normalized, description, min_players, max_players, min_age, max_age, estimated_play_time, can_play_only_once, is_extension, tutorial_url) VALUES (2, 'Bandido', 'bandido', 'Zahraj kartu na zablokovanie všetkých únikov. Ak je bandido zablokovaný, tak ste spoločne vyhrali.', 1, 4, 6, 99, 15, false, false, 'https://www.youtube.com/watch?v=ymkGBJdfclc');"
"INSERT INTO public.board_game (id, title, title_normalized, description, min_players, max_players, min_age, max_age, estimated_play_time, can_play_only_once, is_extension, tutorial_url) VALUES (3, '7 Divů světa: Duel', '7 divu sveta: duel', '', 2, 2, 10, NULL, 30, false, false, 'https://www.youtube.com/watch?v=SxQkMRUvCJ8');"
"INSERT INTO public.board_game (id, title, title_normalized, description, min_players, max_players, min_age, max_age, estimated_play_time, can_play_only_once, is_extension, tutorial_url) VALUES (4, '7 Divů světa: Duel - Agora', '7 divu sveta: duel - agora', '', 2, 2, 10, NULL, 30, false, true, 'https://www.youtube.com/watch?v=6RGu0WhPhMA');"
"INSERT INTO public.board_game (id, title, title_normalized, description, min_players, max_players, min_age, max_age, estimated_play_time, can_play_only_once, is_extension, tutorial_url) VALUES (5, '7 Divů světa: Duel - Pantheon', '7 divu sveta: duel - pantheon', '', 2, 2, 10, NULL, 30, false, true, 'https://www.youtube.com/watch?v=1wG34BYnd1U');"
"INSERT INTO public.board_game (id, title, title_normalized, description, min_players, max_players, min_age, max_age, estimated_play_time, can_play_only_once, is_extension, tutorial_url) VALUES (6, 'Podmořská města', 'podmorska mesta', '', 1, 4, 12, NULL, 40, false, false, 'https://www.youtube.com/watch?v=GHvkzOAgsyM');"
"INSERT INTO public.board_game (id, title, title_normalized, description, min_players, max_players, min_age, max_age, estimated_play_time, can_play_only_once, is_extension, tutorial_url) VALUES (9, 'Bang! - Velká Vlaková Loupež', 'bang! - velka vlakova loupez', '', 4, 7, 8, NULL, 60, false, true, 'https://www.youtube.com/watch?v=pZJUFotCDHs');"
"INSERT INTO public.board_game (id, title, title_normalized, description, min_players, max_players, min_age, max_age, estimated_play_time, can_play_only_once, is_extension, tutorial_url) VALUES (7, 'Bang!', 'bang!', '', 4, 7, 8, NULL, 40, false, false, 'https://www.youtube.com/watch?v=dcanu6cwfxc');"
"INSERT INTO public.board_game (id, title, title_normalized, description, min_players, max_players, min_age, max_age, estimated_play_time, can_play_only_once, is_extension, tutorial_url) VALUES (8, 'Bang! Duel', 'bang! duel', '', 2, 2, 8, NULL, 30, false, false, 'https://www.youtube.com/watch?v=NalXt1Heckk');"
"INSERT INTO public.board_game (id, title, title_normalized, description, min_players, max_players, min_age, max_age, estimated_play_time, can_play_only_once, is_extension, tutorial_url) VALUES (10, 'Človeče nezlob se', 'clovece nezlob se', '', 2, 4, 5, NULL, 30, false, false, NULL);"
"INSERT INTO public.board_game (id, title, title_normalized, description, min_players, max_players, min_age, max_age, estimated_play_time, can_play_only_once, is_extension, tutorial_url) VALUES (11, 'Komu zvoní tramvaj', 'komu zvoni tramvaj', 'Hráči musia rozhodnúť, na ktorú z dvoch koľají pustiť tramvaj, ktorá zmasakruje všetkých, čo na nej stoja. Jeden hráč je výhybkár a ostatní sa rozdelia na dva tímy, ktoré sa snažia presvedčiť výhybkára, aby ich koľaj zachránil a zabil všetkých na tej druhej. Hra je založená na morálnych dilemách.', 3, 13, 15, NULL, 30, false, false, 'https://www.youtube.com/watch?v=F8GzkeWWkR0');"
"INSERT INTO public.board_game (id, title, title_normalized, description, min_players, max_players, min_age, max_age, estimated_play_time, can_play_only_once, is_extension, tutorial_url) VALUES (12, 'Vlajky', 'vlajky', '', 2, 6, 10, NULL, 20, false, false, 'https://www.youtube.com/watch?v=oINxOoUMYfQ');"
"INSERT INTO public.board_game (id, title, title_normalized, description, min_players, max_players, min_age, max_age, estimated_play_time, can_play_only_once, is_extension, tutorial_url) VALUES (13, 'Toulavé Věže', 'toulave veze', 'Študenti mágie absolvujú záverečné skúšky s cieľom doraziť do Havranieho hradu. Cestovať sa dá pešo alebo na cimburiu túlavých veží. Pokiaľ naviac dokážete uzamknúť iných čarodejov, Vaše elixíry sa magicky naplnia. Hráč, ktorý naplní všetky svoje elixíry, najlepšie ich využije a všetkých svojich čarodejov dopraví do Havranieho hradu zvíťazí.', 2, 6, 7, NULL, 30, false, false, 'https://www.youtube.com/watch?v=4sy4BIMQkok');"
"INSERT INTO public.board_game (id, title, title_normalized, description, min_players, max_players, min_age, max_age, estimated_play_time, can_play_only_once, is_extension, tutorial_url) VALUES (14, 'Arnak', 'arnak', 'Uprostred bujnej džungle, v troskách dávno zaniknutej civilizácie, budete objavovať starobylé artefakty, ktoré však strážia desiví ochrancovia.', 1, 4, 12, NULL, 90, false, false, 'https://www.youtube.com/watch?v=GiERdSi5ngI');"
"INSERT INTO public.board_game (id, title, title_normalized, description, min_players, max_players, min_age, max_age, estimated_play_time, can_play_only_once, is_extension, tutorial_url) VALUES (15, 'Jumanji', 'jumanji', '', 2, 4, 8, NULL, 45, false, false, 'https://www.youtube.com/watch?v=qGpNzACCX1E');"
"INSERT INTO public.board_game (id, title, title_normalized, description, min_players, max_players, min_age, max_age, estimated_play_time, can_play_only_once, is_extension, tutorial_url) VALUES (16, 'Mars: Teraformace', 'mars: teraformace', '', 1, 5, 12, NULL, 90, false, false, 'https://www.youtube.com/watch?v=n3yVpsiVwL8');"
"INSERT INTO public.board_game (id, title, title_normalized, description, min_players, max_players, min_age, max_age, estimated_play_time, can_play_only_once, is_extension, tutorial_url) VALUES (17, 'Mars: Teraformace - Předehra', 'mars: teraformace - predehra', '', 1, 5, 12, NULL, 90, false, true, NULL);"
"INSERT INTO public.board_game (id, title, title_normalized, description, min_players, max_players, min_age, max_age, estimated_play_time, can_play_only_once, is_extension, tutorial_url) VALUES (18, 'Mars: Teraformace - Hellas & Elysium', 'mars: teraformace - hellas & elysium', 'Miesto pôvodného herného plánu môžete vyskúšať dva nové. Znázorňujú iné časti Marsu, sú na nich vyznačené iné bonusy za umiestnenie doštičiek, iné oblasti pre doštičky oceánov a nové čestné tituly a súťaže.', 1, 5, 12, NULL, 90, false, true, 'https://www.youtube.com/watch?v=ujq_2n1RKfY');"
"INSERT INTO public.board_game (id, title, title_normalized, description, min_players, max_players, min_age, max_age, estimated_play_time, can_play_only_once, is_extension, tutorial_url) VALUES (19, 'Memoir 44', 'memoir 44', 'Memoir 44 je skvelá ľahká simulácia bitiek 2.svetovej vojny pre dvoch hráčov. Podľa scenáru si najprv vytvoria celkom podrobný plán bitky na univerzálnej hexovej podložke s množstvom žetónov typu pevnosti, ostnatý drôt, vrecia s pieskom, rieka, bunker, zelezničná trať, atď. a umiestnia na scenárom predpísané polia aj jednotky. Jednotky sú pechota, delostrelectvo a tanky, pričom každý druh má elitnú vylepšenú verziu.', 2, 2, 8, NULL, 40, false, false, 'https://www.youtube.com/watch?v=8Cil0XBhYPY');"
"INSERT INTO public.board_game (id, title, title_normalized, description, min_players, max_players, min_age, max_age, estimated_play_time, can_play_only_once, is_extension, tutorial_url) VALUES (20, 'Memoir 44 - Pacific Theater', 'memoir 44 - pacific theater', 'Kompletne nová japonská cisárska armáda, nové dieliky terénov. Jednotlivé scénáre vás potom prevedú slávnými stretmi ako je Iwojima či Okinawa.', 2, 2, 10, NULL, 30, false, true, 'https://www.youtube.com/watch?v=26x8kYWIIKw');"

"INSERT INTO public.author (id, name, name_normalized) VALUES (1, 'Rob Daviau', 'rob daviau');"
"INSERT INTO public.author (id, name, name_normalized) VALUES (2, 'Martin Nedergaard Andersen', 'martin nedergaard andersen');"
"INSERT INTO public.author (id, name, name_normalized) VALUES (3, 'Bruno Cathala', 'bruno cathala');"
"INSERT INTO public.author (id, name, name_normalized) VALUES (4, 'Antoine Bauza', 'antoine bauza');"
"INSERT INTO public.author (id, name, name_normalized) VALUES (5, 'Vladimír Suchý', 'vladimir suchy');"
"INSERT INTO public.author (id, name, name_normalized) VALUES (6, 'Emiliano Sciarra', 'emiliano sciarra');"
"INSERT INTO public.author (id, name, name_normalized) VALUES (7, 'Josef Friedrich Schmidt', 'josef friedrich schmidt');"
"INSERT INTO public.author (id, name, name_normalized) VALUES (8, 'Scott Houser', 'scott houser');"
"INSERT INTO public.author (id, name, name_normalized) VALUES (9, 'Honza Mašek', 'honza masek');"
"INSERT INTO public.author (id, name, name_normalized) VALUES (10, 'Michael Kiesling', 'michael kiesling');"
"INSERT INTO public.author (id, name, name_normalized) VALUES (11, 'Wolfgang Kramer', 'wolfgang kramer');"
"INSERT INTO public.author (id, name, name_normalized) VALUES (12, 'Michal ""Elwen"" Štach', 'michal ""elwen"" stach');"
"INSERT INTO public.author (id, name, name_normalized) VALUES (13, 'Michaela ""Mín"" Štachová', 'michaela ""min"" stachova');"
"INSERT INTO public.author (id, name, name_normalized) VALUES (14, 'Milton Bradley', 'milton bradley');"
"INSERT INTO public.author (id, name, name_normalized) VALUES (15, 'Jacob Fryxelius', 'jacob fryxelius');"
"INSERT INTO public.author (id, name, name_normalized) VALUES (16, 'Richard Borg', 'richard borg');"

"INSERT INTO public.author (id, name, name_normalized) VALUES (1, 1);"
"INSERT INTO public.author (id, name, name_normalized) VALUES (2, 2);"
"INSERT INTO public.author (id, name, name_normalized) VALUES (3, 3);"
"INSERT INTO public.author (id, name, name_normalized) VALUES (3, 4);"
"INSERT INTO public.author (id, name, name_normalized) VALUES (4, 3);"
"INSERT INTO public.author (id, name, name_normalized) VALUES (4, 4);"
"INSERT INTO public.author (id, name, name_normalized) VALUES (5, 3);"
"INSERT INTO public.author (id, name, name_normalized) VALUES (5, 4);"
"INSERT INTO public.author (id, name, name_normalized) VALUES (6, 5);"
"INSERT INTO public.author (id, name, name_normalized) VALUES (7, 6);"
"INSERT INTO public.author (id, name, name_normalized) VALUES (8, 6);"
"INSERT INTO public.author (id, name, name_normalized) VALUES (9, 6);"
"INSERT INTO public.author (id, name, name_normalized) VALUES (10, 7);"
"INSERT INTO public.author (id, name, name_normalized) VALUES (11, 8);"
"INSERT INTO public.author (id, name, name_normalized) VALUES (12, 9);"
"INSERT INTO public.author (id, name, name_normalized) VALUES (13, 10);"
"INSERT INTO public.author (id, name, name_normalized) VALUES (13, 11);"
"INSERT INTO public.author (id, name, name_normalized) VALUES (14, 12);"
"INSERT INTO public.author (id, name, name_normalized) VALUES (14, 13);"
"INSERT INTO public.author (id, name, name_normalized) VALUES (15, 14);"
"INSERT INTO public.author (id, name, name_normalized) VALUES (16, 15);"
"INSERT INTO public.author (id, name, name_normalized) VALUES (17, 15);"
"INSERT INTO public.author (id, name, name_normalized) VALUES (18, 15);"
"INSERT INTO public.author (id, name, name_normalized) VALUES (19, 16);"
"INSERT INTO public.author (id, name, name_normalized) VALUES (20, 16);"
